# Generated by Django 6.0 on 2026-01-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('interval_value', models.IntegerField(default=8)),
                ('interval_unit', models.CharField(default='hour', max_length=20)),
                ('last_taken', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('count_after_intake', models.IntegerField()),
                ('pill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medications.pill')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
