# Generated by Django 6.0 on 2026-01-03 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={},
        ),
        migrations.AddField(
            model_name='history',
            name='pill_name',
            field=models.CharField(default='Old Medicine', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='history',
            name='pill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='medications.pill'),
        ),
    ]
