# Generated by Django 6.0 on 2026-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_history_options_history_pill_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='next_expected_intake',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
