# Generated by Django 6.0 on 2026-01-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_expopushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
