# Generated by Django 6.0 on 2026-01-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0005_pill_is_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='pill',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
